### ISSUE TITLE
snippy install on OS X (chapmanb/cbl/vcflib 2015-03-13 did not build)

### ISSUE THREAD

**Issue by gawbul** [chapmanb/homebrew-cbl#22]
Getting the following error when trying to install `snippy` on OSX:

**Error: chapmanb/cbl/vcflib 2015-03-13 did not build**

```
cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
ar -cru libtabix.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [libtabix.a] Error 1
make[1]: *** [all-recur] Error 1
make: *** [tabixpp/tabix.o] Error 2
```

I applied the fixes for this issue as listed here https://github.com/Homebrew/homebrew-science/pull/2092 to get it to install `snippy` (and `vcflib`) correctly.

Reported upstream in `snippy` too (cc @tseemann)

**Comment by chapmanb** [comment]
Steve -- thank you for the heads up on the issue. I don't have a Mac to test on but applied Torsten's patches so hopefully it works for you now. Out of curiosity, where is the snippy recipe you're using? I didn't spot that in any of the repositories I know of.

Torsten, it's great you're working on getting vcflib into homebrew-science. Thanks for doing that. Is there any reason you're using an older build (20140412) instead of something more recent there? I know release versions would help but in general I've been trying to track different up to date versions from GitHub. Thanks for all this work.

**Comment by tseemann** [comment]
Brad, Snippy is in my brew repository: https://github.com/tseemann/homebrew-bioinformatics-linux (haploid only)
The Homebrew folks forced me to tag a version back then and I haven't got back to updating it. At the time that was the "stable" one you trusted. I've nearly got it into Brew-sci, it's been slow.

**Comment by chapmanb** [comment]
Torsten -- thanks for the background, that all makes lot more sense now. Thanks for helping try to push this into homebrew-science, your patience is legendary.

**Comment by tseemann** [comment]
It's in!
https://github.com/Homebrew/homebrew-science/blob/master/vcflib.rb

**Comment by chapmanb** [comment]
Torsten -- thanks again. I dropped the vcflib in this repo and will submit any fixes/patches to homebrew-science. Nice work.
